#pragma once
class Ids
{
private:
	Ids() {};
	~Ids() {};
public:
	enum
	{
		INDEX_START = 10000,

		// EditorStates
		ID_IMPORT_STATES, ID_EXPORT_STATES, ID_EXIT_STATES,
		ID_CLOSE_STATES, ID_SAVE_STATES, ID_SAVE_CLOSE_STATES,
		ID_FIND_STATES, ID_REPLACE_STATES, ID_FORMAT_STATES,
		ID_MARK_NEXT_STATES, ID_MARK_PREV_STATES,
		ID_HELP_STATES,

		// EditorRules
		ID_IMPORT_RULES, ID_EXPORT_RULES, ID_EXIT_RULES,
		ID_CLOSE_RULES, ID_SAVE_RULES, ID_SAVE_CLOSE_RULES,
		ID_FIND_RULES, ID_REPLACE_RULES, ID_FORMAT_RULES,
		ID_MARK_NEXT_RULES, ID_MARK_PREV_RULES,
		ID_HELP_RULES,

		// MenuBar
		ID_IMPORT, ID_EXPORT, ID_EXIT,
		ID_VIEW_DEFAULT, ID_VIEW_GRID, ID_VIEW_STATES, ID_VIEW_RULES, ID_VIEW_DIMENSIONS, ID_VIEW_FULLSCREEN,
		ID_USERMANUAL, ID_SHORTCUTS,

		// InputStates
		ID_EDIT_STATES,
		ID_SEARCH_STATES,
		ID_SELECT_STATE,
		ID_GOTO_STATE,
		ID_COLOR_STATE,
		ID_ERASE_STATE,
		ID_DELETE_STATE,

		// InputNeighbors
		ID_NEIGHBOR_NW, ID_NEIGHBOR_N, ID_NEIGHBOR_NE,
		ID_NEIGHBOR_W, ID_NEIGHBOR_C, ID_NEIGHBOR_E,
		ID_NEIGHBOR_SW, ID_NEIGHBOR_S, ID_NEIGHBOR_SE,

		// InputRules
		ID_EDIT_RULES,
		ID_SEARCH_RULES,
		ID_GOTO_RULE,
		ID_DELETE_RULE,

		// ToolZoom
		ID_ZOOM_OUT, ID_ZOOM_IN,

		// ToolUndo
		ID_BUTTON_UNDO, ID_BUTTON_REDO,

		// ToolModes
		ID_MODE_DRAW, ID_MODE_PICK, ID_MODE_MOVE,

		// ToolStates
		ID_BUTTON_PREV, ID_BUTTON_NEXT,

		// StatusSpeed
		ID_BUTTON_FASTER, ID_BUTTON_SLOWER,

		// StatusControls
		ID_BUTTON_CENTER,
		ID_BUTTON_PLAY, ID_BUTTON_RESET, ID_BUTTON_POPULATE,
		ID_BUTTON_STEP, ID_BUTTON_GENERATION,

		// HelpWindow
		ID_CONTENTS_HELP, ID_CLOSE_HELP, ID_PREV_HELP, ID_NEXT_HELP,

		// timers
		ID_TIMER_SELECTION, ID_TIMER_ELAPSED,

		// AlgorithmOutput
		ID_OUTPUT_START, ID_OUTPUT_STOP, ID_OUTPUT_SAVE
	};
};

